name: Django CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r template-jango/requirements/local.txt

      - name: Run Tests
        env:
          POSTGRES_NAME: test_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
        run: |
          cd template-jango/proyecto_django
          # Configurar base de datos para pruebas
          sed -i 's/"NAME":""/"NAME":"test_db"/g' proyecto_django/settings/local.py
          sed -i 's/"USER":""/"USER":"postgres"/g' proyecto_django/settings/local.py
          sed -i 's/"PASSWORD":""/"PASSWORD":"postgres"/g' proyecto_django/settings/local.py
          sed -i 's/"HOST":""/"HOST":"localhost"/g' proyecto_django/settings/local.py
          sed -i 's/"PORT":""/"PORT":"5432"/g' proyecto_django/settings/local.py
          # Corregir formato de MEDIA_ROOT
          sed -i "s/MEDIA_ROOT = \[BASE_DIR \/ 'media'\]/MEDIA_ROOT = BASE_DIR \/ 'media'/g" proyecto_django/settings/local.py
          # Ejecutar pruebas
          python manage.py test
